export const categories = [
  { value: "novel", label: "小説" },
  { value: "non-fiction", label: "ノンフィクション" },
  { value: "self-help", label: "自己啓発" },
  { value: "business", label: "ビジネス" },
  { value: "science", label: "科学" },
  { value: "history", label: "歴史" },
  { value: "biography", label: "伝記" },
  { value: "travel", label: "旅行" },
  { value: "cookbook", label: "料理" },
  { value: "children", label: "児童書" },
  { value: "art", label: "芸術・写真" },
  { value: "computer", label: "IT・コンピューター" },
  { value: "technology", label: "テクノロジー" },
  { value: "health", label: "健康・医学" },
  { value: "education", label: "教育・学習" },
  { value: "young_adult", label: "ヤングアダルト" },
  { value: "poetry", label: "詩" },
  { value: "religion", label: "宗教・スピリチュアル" },
  { value: "sports", label: "スポーツ" },
];
