import {
  BabyIcon,
  BookCheckIcon,
  BookHeartIcon,
  BookTextIcon,
  BriefcaseBusinessIcon,
  CookingPotIcon,
  CpuIcon,
  DumbbellIcon,
  EarthIcon,
  FlaskConicalIcon,
  GraduationCap,
  HeartHandshakeIcon,
  HistoryIcon,
  MedalIcon,
  NotebookPenIcon,
  PaletteIcon,
  PersonStandingIcon,
  PlaneIcon,
  SettingsIcon,
} from "lucide-react";

export const categoryIcons: { [key: string]: React.JSX.Element } = {
  novel: <BookTextIcon />,
  "non-fiction": <BookCheckIcon />,
  "self-help": <HeartHandshakeIcon />,
  business: <BriefcaseBusinessIcon />,
  science: <FlaskConicalIcon />,
  history: <HistoryIcon />,
  biography: <NotebookPenIcon />,
  travel: <PlaneIcon />,
  cookbook: <CookingPotIcon />,
  children: <BabyIcon />,
  art: <PaletteIcon />,
  computer: <CpuIcon />,
  technology: <SettingsIcon />,
  health: <DumbbellIcon />,
  education: <GraduationCap />,
  young_adult: <PersonStandingIcon />,
  poetry: <BookHeartIcon />,
  religion: <EarthIcon />,
  sports: <MedalIcon />,
};
