export const categories = [
  { category: "novel", label: "小説" },
  { category: "non-fiction", label: "ノンフィクション" },
  { category: "self-help", label: "自己啓発" },
  { category: "business", label: "ビジネス" },
  { category: "science", label: "科学" },
  { category: "history", label: "歴史" },
  { category: "biography", label: "伝記" },
  { category: "travel", label: "旅行" },
  { category: "cookbook", label: "料理" },
  { category: "children", label: "児童書" },
  { category: "art", label: "芸術・写真" },
  { category: "computer", label: "IT・コンピューター" },
  { category: "technology", label: "テクノロジー" },
  { category: "health", label: "健康・医学" },
  { category: "education", label: "教育・学習" },
  { category: "young_adult", label: "ヤングアダルト" },
  { category: "poetry", label: "詩" },
  { category: "religion", label: "宗教・スピリチュアル" },
  { category: "sports", label: "スポーツ" },
];
