import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "@/app/globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} antialiased`}
      >
        {children}
        <Script
          async 
          src="https://cloud.umami.is/script.js" 
          data-website-id={process.env.UMAMI_DABA_WEBSITE_ID} />
      </body>
    </html>
  );
}
