name: Deploy

on:
  workflow_dispatch:
  pull_request:
    branches:
      - feature
      - task
      - fix
    types: [opened, reopened, synchronize]

env:
  VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./app
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run format
      - run: npm run test
      - run: npm i --global vercel@latest
      - run: vercel pull --yes --environment=preview --token=${{ env.VERCEL_TOKEN }}
      - run: vercel build --token=${{ env.VERCEL_TOKEN }}
      - run: vercel deploy --token=${{ env.VERCEL_TOKEN }}