name: CI

on:
  push:
    branches-ignore:
      - main
      - dev

env:
  WORKING_DIRECTORY: "./app"

jobs:
  setup:
    if: github.event_name != 'pull_request' || github.event.action != 'opened'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.WORKING_DIRECTORY }}
    permissions:
      contents: read
    outputs:
      cache-key: ${{ steps.npm-cache.outputs.cache-key }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Get cache key
        id: npm-cache
        run: echo "cache-key=npm-${{ hashFiles('**/package-lock.json') }}" >> $GITHUB_OUTPUT
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ${{ env.WORKING_DIRECTORY }}/node_modules
          key: ${{ steps.npm-cache.outputs.cache-key }}
          restore-keys: |
            npm-
      - name: Install dependencies
        run: npm ci

  lint:
    needs: setup
    uses: ./.github/workflows/lint.yml
    with:
      working-directory: "./app"
      cache-key: ${{ needs.setup.outputs.cache-key }}

  test:
    needs: setup
    uses: ./.github/workflows/test.yml
    with:
      working-directory: "./app"
      cache-key: ${{ needs.setup.outputs.cache-key }}
